datamodule:
  encoder: /notebook/temp/task2encoder.pkl
  dataset_path: /notebook/temp/CASIA-HWDB_Train/Train
  valid:
    batch_size: 1024
    num_workers: 10
  train:
    batch_size: 1024
    num_workers: 8

module:
  backbone: resnet34
  feature_size: 512
  num_classes: 7330
  monitor_metric: val_loss
  monitor_mode: min
  use_focal_loss: true
  optimizer:
    name: SGD
    params:
      lr: 0.001
      momentum: 0.9
      nesterov: True
      weight_decay: 0.0001

trainer:
  gpus: -1
  accelerator: "gpu"
  precision: 32
  benchmark: True
  max_epochs: 50
#  fast_dev_run: True
  accumulate_grad_batches: 2


logging:
  logdir: resnset34
  experiment_name: arcface
